import React, { useEffect, useState } from 'react';
import { getPublishedStateRecords, formatStateRecordTime } from '../services/stateRecords.js';

const categoryKey = (name) => name.normalize('NFKC').toLocaleLowerCase('es');
const tabId = (name) => encodeURIComponent(categoryKey(name));

const RecordCard = ({ record }) => <li className="grid min-w-0 gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900 sm:grid-cols-[64px_minmax(0,1fr)_auto] sm:items-center">
  {record.photoUrl ? <img src={record.photoUrl} alt={record.photoAlt} width="64" height="64" loading="lazy" className="h-16 w-16 rounded-full object-cover" /> : <span role="img" aria-label={`Sin foto de ${record.athleteName}`} className="flex h-16 w-16 items-center justify-center rounded-full bg-cyan-100 font-bold text-asanda-deep dark:bg-slate-700 dark:text-cyan-200">{record.fallback}</span>}
  <div className="min-w-0"><p className="font-bold text-slate-950 dark:text-white">{record.athleteName}</p><p className="break-words text-sm text-slate-600 dark:text-slate-300">{record.clubName} · {record.competitionName} · {record.achievedYear}</p><p className="mt-1 font-medium text-slate-800 dark:text-slate-100">{record.eventName}</p></div>
  <strong className="text-xl tabular-nums text-asanda-deep dark:text-cyan-300">{formatStateRecordTime(record.timeMs)}</strong>
</li>;

const RecordSection = ({ id, title, records }) => <section aria-labelledby={id} className="mt-8"><h3 id={id} className="text-2xl font-bold text-slate-950 dark:text-white">{title}</h3>{records.length ? <ul className="mt-4 space-y-3">{records.map((record) => <RecordCard key={record.id} record={record} />)}</ul> : <p className="mt-4 rounded-xl border border-dashed border-slate-300 p-6 text-slate-600 dark:border-slate-700 dark:text-slate-300">No hay récords publicados en {title.toLowerCase()} para esta categoría.</p>}</section>;

const RecordEstadal = () => {
  const [records, setRecords] = useState([]); const [status, setStatus] = useState('loading'); const [retry, setRetry] = useState(0); const [activeCategory, setActiveCategory] = useState('');
  useEffect(() => { const controller = new AbortController(); setStatus('loading'); getPublishedStateRecords(controller.signal).then((items) => { setRecords(items); setStatus('ready'); }).catch(() => { if (!controller.signal.aborted) setStatus('error'); }); return () => controller.abort(); }, [retry]);
  const categories = [...new Map(records.map((record) => [categoryKey(record.categoryName), record.categoryName])).values()].sort((a, b) => a.localeCompare(b, 'es', { sensitivity: 'base' }));
  useEffect(() => { if (categories.length && !categories.some((name) => categoryKey(name) === categoryKey(activeCategory))) setActiveCategory(categories[0]); }, [activeCategory, categories]);
  const onTabKeyDown = (event) => { const tabs = [...event.currentTarget.parentElement.querySelectorAll('[role="tab"]')]; const index = tabs.indexOf(event.currentTarget); const next = event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : event.key === 'ArrowRight' ? (index + 1) % tabs.length : event.key === 'ArrowLeft' ? (index - 1 + tabs.length) % tabs.length : -1; if (next >= 0) { event.preventDefault(); tabs[next].focus(); setActiveCategory(tabs[next].dataset.category); } };

  return <section id="record-estadal" aria-busy={status === 'loading'} className="min-w-0 bg-slate-50 py-12 dark:bg-slate-950"><div className="container mx-auto min-w-0 px-4"><h2 className="text-3xl font-bold text-slate-950 dark:text-white">Récords publicados</h2><p className="mt-2 text-slate-600 dark:text-slate-300">Mejores tiempos oficiales de piscina larga en el estado Anzoátegui.</p>
    {status === 'loading' && <p role="status" className="mt-8 min-h-48 rounded-xl border border-slate-200 bg-white p-6 text-slate-700 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">Cargando récords estadales…</p>}
    {status === 'error' && <div role="alert" className="mt-8 rounded-xl border border-red-200 bg-red-50 p-6 text-red-800 dark:border-red-900 dark:bg-red-950 dark:text-red-200"><p>No pudimos cargar los récords estadales.</p><button type="button" onClick={() => setRetry((value) => value + 1)} className="mt-4 min-h-11 rounded-lg border border-current px-4 font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2">Reintentar</button></div>}
    {status === 'ready' && !records.length && <p role="status" className="mt-8 rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">Todavía no hay récords estadales publicados.</p>}
    {status === 'ready' && records.length > 0 && <><div role="tablist" aria-label="Categorías históricas" className="mt-8 flex max-w-full gap-2 overflow-x-auto border-b border-slate-300 pb-2 dark:border-slate-700">{categories.map((category) => { const active = categoryKey(category) === categoryKey(activeCategory); const id = tabId(category); return <button key={id} id={`record-tab-${id}`} type="button" role="tab" data-category={category} aria-selected={active} aria-controls={`record-panel-${id}`} tabIndex={active ? 0 : -1} onClick={() => setActiveCategory(category)} onKeyDown={onTabKeyDown} className={`min-h-11 shrink-0 rounded-t-lg px-4 font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-asanda-orange ${active ? 'bg-asanda-deep text-white' : 'text-slate-700 dark:text-slate-200'}`}>{category}</button>; })}</div>{categories.map((category) => { const active = categoryKey(category) === categoryKey(activeCategory); const id = tabId(category); const categoryRecords = records.filter((record) => categoryKey(record.categoryName) === categoryKey(category)); return <div key={id} id={`record-panel-${id}`} role="tabpanel" aria-labelledby={`record-tab-${id}`} hidden={!active} tabIndex={0}><RecordSection id={`record-${id}-female`} title="Femenino" records={categoryRecords.filter((record) => record.sex === 'female')} /><RecordSection id={`record-${id}-male`} title="Masculino" records={categoryRecords.filter((record) => record.sex === 'male')} /></div>; })}</>}
  </div></section>;
};

export default RecordEstadal;
