import React, { useEffect, useState } from 'react';
import { getPublicStateRecordsPageData, formatStateRecordTime } from '../services/stateRecords.js';

const categoryKey = (name) => name.trim().replace(/\s+/g, ' ').normalize('NFKC').toLocaleLowerCase('es');

const AthletePhoto = ({ record, desktop = false }) => {
  const size = desktop ? 56 : 80; const classes = `${desktop ? 'h-14 w-14' : 'h-20 w-20'} shrink-0 rounded-full object-cover`;
  return record.photoUrl ? <img src={record.photoUrl} alt={record.photoAlt} width={size} height={size} loading="lazy" className={classes} /> : <span role="img" aria-label={`Sin foto de ${record.athleteName}`} className={`flex ${classes} items-center justify-center bg-cyan-100 font-bold text-asanda-deep dark:bg-slate-700 dark:text-cyan-200`}>{record.fallback}</span>;
};

const RecordCard = ({ record }) => <li className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900">
  <div className="flex min-w-0 items-start justify-between gap-3"><h4 className="min-w-0 break-words font-bold text-slate-950 dark:text-white">{record.eventName}</h4><strong className="shrink-0 text-2xl tabular-nums text-asanda-deep dark:text-cyan-300">{formatStateRecordTime(record.timeMs)}</strong></div>
  <div className="mt-4 flex min-w-0 items-center gap-4"><AthletePhoto record={record} /><div className="min-w-0"><p className="break-words font-bold text-slate-950 dark:text-white">{record.athleteName}</p><p className="break-words text-sm text-slate-600 dark:text-slate-300">{record.clubName}</p></div></div>
  <dl className="mt-4 grid min-w-0 grid-cols-[auto_minmax(0,1fr)] gap-x-3 gap-y-1 border-t border-slate-200 pt-3 text-sm dark:border-slate-700"><dt className="font-semibold text-slate-700 dark:text-slate-200">Año</dt><dd className="text-slate-900 dark:text-white">{record.achievedYear}</dd><dt className="font-semibold text-slate-700 dark:text-slate-200">Competencia</dt><dd className="min-w-0 break-words text-slate-900 dark:text-white">{record.competitionName}</dd></dl>
</li>;

const RecordTable = ({ id, records }) => <div className="mt-4 hidden overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900 lg:block"><table aria-labelledby={id} className="w-full table-fixed border-collapse"><thead className="bg-asanda-deep text-left text-sm uppercase tracking-wide text-white"><tr><th scope="col" className="w-[19%] px-5 py-4">Prueba</th><th scope="col" className="w-[13%] px-5 py-4">Récord</th><th scope="col" className="w-[30%] px-5 py-4">Atleta / Club</th><th scope="col" className="w-[10%] px-5 py-4">Año</th><th scope="col" className="w-[28%] px-5 py-4">Competencia</th></tr></thead><tbody className="divide-y divide-slate-200 dark:divide-slate-700">{records.map((record) => <tr key={record.id} className="outline-none hover:relative hover:z-10 hover:shadow-[inset_0_0_0_2px_currentColor] focus-within:relative focus-within:z-10 focus-within:shadow-[inset_0_0_0_2px_currentColor]"><th scope="row" className="break-words px-5 py-4 text-left font-semibold text-slate-900 dark:text-white">{record.eventName}</th><td className="px-5 py-4"><strong className="text-2xl tabular-nums text-asanda-deep dark:text-cyan-300">{formatStateRecordTime(record.timeMs)}</strong></td><td className="px-5 py-3"><div className="flex min-w-0 items-center gap-3"><AthletePhoto record={record} desktop /><div className="min-w-0"><p className="break-words font-bold text-slate-950 dark:text-white">{record.athleteName}</p><p className="break-words text-sm text-slate-600 dark:text-slate-300">{record.clubName}</p></div></div></td><td className="px-5 py-4 tabular-nums text-slate-800 dark:text-slate-100">{record.achievedYear}</td><td className="break-words px-5 py-4 text-slate-800 dark:text-slate-100">{record.competitionName}</td></tr>)}</tbody></table></div>;

const RecordSection = ({ id, title, records }) => <section aria-labelledby={id} className="mt-8"><h3 id={id} className="text-2xl font-bold text-slate-950 dark:text-white">{title}</h3>{records.length ? <><ul aria-labelledby={id} className="mt-4 space-y-3 lg:hidden">{records.map((record) => <RecordCard key={record.id} record={record} />)}</ul><RecordTable id={id} records={records} /></> : <p className="mt-4 rounded-xl border border-dashed border-slate-300 p-6 text-slate-600 dark:border-slate-700 dark:text-slate-300">No hay récords publicados en {title.toLowerCase()} para esta categoría.</p>}</section>;

const RecordEstadal = () => {
  const [records, setRecords] = useState([]); const [categories, setCategories] = useState([]); const [status, setStatus] = useState('loading'); const [retry, setRetry] = useState(0); const [activeCategory, setActiveCategory] = useState('');
  useEffect(() => { const controller = new AbortController(); setStatus('loading'); getPublicStateRecordsPageData(controller.signal).then((data) => { setRecords(data.records); setCategories(data.categories); setActiveCategory((current) => data.categories.some((category) => category.code === current) ? current : data.categories[0].code); setStatus('ready'); }).catch(() => { if (!controller.signal.aborted) setStatus('error'); }); return () => controller.abort(); }, [retry]);
  const onTabKeyDown = (event) => { const tabs = [...event.currentTarget.parentElement.querySelectorAll('[role="tab"]')]; const index = tabs.indexOf(event.currentTarget); const next = event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : event.key === 'ArrowRight' ? (index + 1) % tabs.length : event.key === 'ArrowLeft' ? (index - 1 + tabs.length) % tabs.length : -1; if (next >= 0) { event.preventDefault(); tabs[next].focus(); setActiveCategory(tabs[next].dataset.category); } };

  return <section id="record-estadal" aria-busy={status === 'loading'} className="min-w-0 bg-slate-50 py-12 dark:bg-slate-950"><div className="container mx-auto min-w-0 px-4"><h2 className="text-3xl font-bold text-slate-950 dark:text-white">Récords publicados</h2><p className="mt-2 text-slate-600 dark:text-slate-300">Mejores tiempos oficiales de piscina larga en el estado Anzoátegui.</p>
    {status === 'loading' && <p role="status" className="mt-8 min-h-48 rounded-xl border border-slate-200 bg-white p-6 text-slate-700 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">Cargando récords estadales…</p>}
    {status === 'error' && <div role="alert" className="mt-8 rounded-xl border border-red-200 bg-red-50 p-6 text-red-800 dark:border-red-900 dark:bg-red-950 dark:text-red-200"><p>No pudimos cargar los récords estadales.</p><button type="button" onClick={() => setRetry((value) => value + 1)} className="mt-4 min-h-11 rounded-lg border border-current px-4 font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2">Reintentar</button></div>}
    {status === 'ready' && !records.length && <p role="status" className="mt-8 rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">Todavía no hay récords estadales publicados.</p>}
    {status === 'ready' && <><div role="tablist" aria-label="Categorías históricas" className="mt-8 flex max-w-full gap-2 overflow-x-auto border-b border-slate-300 pb-2 dark:border-slate-700">{categories.map((category) => { const active = category.code === activeCategory; const id = category.code; return <button key={id} id={`record-tab-${id}`} type="button" role="tab" data-category={category.code} aria-selected={active} aria-controls={`record-panel-${id}`} tabIndex={active ? 0 : -1} onClick={() => setActiveCategory(category.code)} onKeyDown={onTabKeyDown} className={`min-h-11 shrink-0 rounded-t-lg px-4 font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-asanda-orange ${active ? 'bg-asanda-deep text-white' : 'text-slate-700 dark:text-slate-200'}`}>{category.label}</button>; })}</div>{categories.map((category) => { const active = category.code === activeCategory; const id = category.code; const categoryRecords = records.filter((record) => categoryKey(record.categoryName) === categoryKey(category.name)); return <div key={id} id={`record-panel-${id}`} role="tabpanel" aria-labelledby={`record-tab-${id}`} hidden={!active} tabIndex={0}><RecordSection id={`record-${id}-female`} title="Femenino" records={categoryRecords.filter((record) => record.sex === 'female')} /><RecordSection id={`record-${id}-male`} title="Masculino" records={categoryRecords.filter((record) => record.sex === 'male')} /></div>; })}</>}
  </div></section>;
};

export default RecordEstadal;
