import React, { useCallback, useEffect, useState } from 'react';
import { getAdminMediaUrl } from '../services/admin/media';
import { formatRecordError, formatRecordTime, getRecordReferences, listStateRecords, saveStateRecordDraft, setStateRecordPublished } from '../services/admin/records';

const field = 'mt-2 min-h-11 w-full rounded-md border border-asanda-line bg-white px-3 text-asanda-ink disabled:bg-slate-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-asanda-orange dark:border-slate-600 dark:bg-slate-800 dark:text-white dark:disabled:bg-slate-700';
const panel = 'rounded-[14px] border border-asanda-line bg-white p-5 dark:border-slate-700 dark:bg-dark-surface';
const empty = { id: '', revision: '', athleteId: '', athleteName: '', photoAssetId: '', clubName: '', eventDefinitionId: '', ageCategoryId: '', competitiveSex: 'female', time: '', achievedYear: '', competitionName: '', publicationStatus: 'draft' };
const toForm = (row) => ({ id: row.id, revision: row.revision, athleteId: row.athlete_id || '', athleteName: row.athlete_name_snapshot, photoAssetId: row.athlete_photo_asset_id || '', clubName: row.club_name_snapshot, eventDefinitionId: row.event_definition_id, ageCategoryId: row.age_category_id, competitiveSex: row.competitive_sex, time: formatRecordTime(row.time_ms), achievedYear: String(row.achieved_year), competitionName: row.competition_name_snapshot, publicationStatus: row.publication_status });

export default function AdminRecordsPage() {
  const [records, setRecords] = useState(null); const [refs, setRefs] = useState(null); const [form, setForm] = useState(empty); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setRecords(null); setNotice(null); try { const [items, references] = await Promise.all([listStateRecords(), getRecordReferences()]); setRecords(items); setRefs(references); } catch { setNotice({ error: true, text: 'No fue posible cargar los récords. Intentá nuevamente.' }); } }, []);
  useEffect(() => { load(); }, [load]);
  const update = (name, value) => setForm((current) => ({ ...current, [name]: value }));
  const chooseAthlete = (athleteId) => { const athlete = refs.athletes.find((item) => item.id === athleteId); setForm((current) => ({ ...current, athleteId, athleteName: athlete?.display_name || current.athleteName, photoAssetId: athlete?.photo_asset_id || current.photoAssetId })); };
  const save = async (event) => { event.preventDefault(); setBusy(true); setNotice(null); try { const saved = await saveStateRecordDraft(form); setNotice({ text: 'Borrador guardado.' }); setForm((current) => ({ ...current, id: saved.record_id, revision: saved.revision })); setRecords(await listStateRecords()); } catch (error) { setNotice({ error: true, text: formatRecordError(error) }); } finally { setBusy(false); } };
  const publish = async (row) => { setBusy(true); setNotice(null); try { await setStateRecordPublished(row, row.publication_status !== 'published'); setNotice({ text: row.publication_status === 'published' ? 'Récord despublicado.' : 'Récord publicado.' }); const items = await listStateRecords(); setRecords(items); const selected = items.find((item) => item.id === form.id); if (selected) setForm(toForm(selected)); } catch (error) { setNotice({ error: true, text: formatRecordError(error) }); } finally { setBusy(false); } };
  const selectedPhoto = refs?.media.find((asset) => asset.id === form.photoAssetId); const locked = form.publicationStatus === 'published';
  return <section aria-labelledby="records-title" className="space-y-6">
    <div><p className="text-xs font-bold uppercase tracking-[0.16em] text-asanda-deep dark:text-slate-300">Historia deportiva</p><h1 id="records-title" className="mt-2 font-display text-3xl font-bold sm:text-4xl">Récords</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Récords estadales de piscina larga. Categoría y club son datos históricos editables.</p></div>
    <div aria-live="polite">{notice && <p role={notice.error ? 'alert' : 'status'} className={`rounded-md border p-4 text-sm font-semibold ${notice.error ? 'border-red-200 bg-red-50 text-red-800' : 'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{notice.text}{notice.error && !records && <button type="button" onClick={load} className="ml-3 font-bold underline">Reintentar</button>}</p>}</div>
    {!records && !notice && <p role="status" className={panel}>Cargando récords…</p>}
    {records && refs && <div className="grid min-w-0 gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]">
      <section className={`${panel} min-w-0 space-y-4`} aria-labelledby="record-list-title"><div className="flex items-center justify-between gap-3"><h2 id="record-list-title" className="text-xl font-bold">Registros</h2><button type="button" onClick={() => setForm(empty)} className="min-h-10 font-bold text-asanda-deep dark:text-white">Nuevo</button></div>{records.length === 0 && <p>Todavía no hay récords estadales.</p>}<ul className="space-y-3">{records.map((row) => <li key={row.id} className="rounded-md border border-asanda-line p-3"><p className="font-bold">{row.athlete_name_snapshot}</p><p className="text-sm">{row.event_name_snapshot} · {row.age_category_name_snapshot} · {formatRecordTime(row.time_ms)}</p><p className="mt-1 text-xs font-bold uppercase">{row.publication_status === 'published' ? 'Publicado' : 'Borrador'}</p><div className="mt-2 flex flex-wrap gap-3"><button type="button" onClick={() => setForm(toForm(row))} className="min-h-10 font-bold text-asanda-deep dark:text-white">Ver registro</button><button type="button" disabled={busy} onClick={() => publish(row)} className="min-h-10 font-bold text-asanda-orange disabled:opacity-60">{row.publication_status === 'published' ? 'Despublicar' : 'Publicar'}</button></div></li>)}</ul></section>
      <form className={`${panel} grid min-w-0 gap-5 sm:grid-cols-2`} onSubmit={save}><div className="sm:col-span-2"><h2 className="text-xl font-bold">{form.id ? 'Registro seleccionado' : 'Nuevo borrador'}</h2>{locked && <p className="mt-2 text-sm font-semibold text-amber-800 dark:text-amber-300">Despublicá este récord antes de editarlo.</p>}</div>
        <fieldset disabled={locked || busy} className="grid gap-3 rounded-md border border-asanda-line p-4 sm:col-span-2"><legend className="px-2 font-bold">Origen del atleta</legend><label><input type="radio" name="origin" checked={!form.athleteId} onChange={() => update('athleteId', '')} /> Histórico manual</label><label><input type="radio" name="origin" checked={Boolean(form.athleteId)} onChange={() => chooseAthlete(refs.athletes[0]?.id || '')} /> Atleta existente</label>{form.athleteId && <label className="text-sm font-bold">Atleta<select className={field} value={form.athleteId} onChange={(event) => chooseAthlete(event.target.value)}>{refs.athletes.map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label>}</fieldset>
        <label className="text-sm font-bold">Nombre histórico<input className={field} disabled={locked} required value={form.athleteName} onChange={(event) => update('athleteName', event.target.value)} /></label><label className="text-sm font-bold">Club histórico<input className={field} disabled={locked} required value={form.clubName} onChange={(event) => update('clubName', event.target.value)} /></label>
        <label className="text-sm font-bold sm:col-span-2">Foto pública opcional<select className={field} disabled={locked} value={form.photoAssetId} onChange={(event) => update('photoAssetId', event.target.value)}><option value="">Sin foto</option>{refs.media.map((asset) => <option key={asset.id} value={asset.id}>{asset.altText}</option>)}</select></label>{selectedPhoto && <img className="h-28 w-28 rounded-md object-cover sm:col-span-2" src={getAdminMediaUrl(selectedPhoto, { width: 224, height: 224 })} alt={selectedPhoto.altText} />}
        <label className="text-sm font-bold">Prueba (piscina larga)<select className={field} disabled={locked} required value={form.eventDefinitionId} onChange={(event) => update('eventDefinitionId', event.target.value)}><option value="">Seleccioná una prueba…</option>{refs.definitions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-bold">Categoría histórica<select className={field} disabled={locked} required value={form.ageCategoryId} onChange={(event) => update('ageCategoryId', event.target.value)}><option value="">Seleccioná una categoría…</option>{refs.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
        <label className="text-sm font-bold">Género<select className={field} disabled={locked} value={form.competitiveSex} onChange={(event) => update('competitiveSex', event.target.value)}><option value="female">Femenino</option><option value="male">Masculino</option></select></label><label className="text-sm font-bold">Tiempo<input className={field} disabled={locked} required placeholder="1:02.35" inputMode="decimal" value={form.time} onChange={(event) => update('time', event.target.value)} /></label>
        <label className="text-sm font-bold">Año<input className={field} disabled={locked} required type="number" min="1900" max="2200" value={form.achievedYear} onChange={(event) => update('achievedYear', event.target.value)} /></label><label className="text-sm font-bold">Competencia<input className={field} disabled={locked} required value={form.competitionName} onChange={(event) => update('competitionName', event.target.value)} /></label>
        {!locked && <button type="submit" disabled={busy} className="min-h-11 rounded-md bg-asanda-deep px-5 font-bold text-white disabled:opacity-60 sm:col-span-2 sm:justify-self-start">{busy ? 'Guardando…' : 'Guardar borrador'}</button>}
      </form></div>}
  </section>;
}
