import React, { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, FileCheck2, RefreshCw, Upload, Users } from 'lucide-react';
import { getResultReferences, listResultCompetitions, parseResultFile, reconcileResultPreview, saveResultMapping, formatResultImportError } from '../services/admin/results.js';

const panel = 'rounded-[14px] border border-asanda-line bg-white p-5 dark:border-slate-700 dark:bg-dark-surface sm:p-6';
const field = 'mt-2 min-h-11 w-full rounded-md border border-asanda-line bg-white px-3 text-asanda-ink focus-visible:outline focus-visible:outline-2 focus-visible:outline-asanda-orange dark:border-slate-600 dark:bg-slate-800 dark:text-white';
const targetName = (item) => item?.short_name || item?.display_name || item?.name || item?.id || '—';
const Notice = ({ notice }) => notice ? <p role={notice.error ? 'alert' : 'status'} className={`rounded-md border p-4 text-sm font-semibold ${notice.error ? 'border-red-200 bg-red-50 text-red-800 dark:border-red-900 dark:bg-red-950 dark:text-red-100' : 'border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-100'}`}>{notice.text}</p> : null;

export default function AdminResultsPage() {
  const [competitions, setCompetitions] = useState(null); const [competitionId, setCompetitionId] = useState(''); const [references, setReferences] = useState(null);
  const [file, setFile] = useState(null); const [result, setResult] = useState(null); const [notice, setNotice] = useState(null); const [busy, setBusy] = useState(false);
  const loadCompetitions = useCallback(async () => { try { setCompetitions(await listResultCompetitions()); } catch { setNotice({ error: true, text: 'No fue posible cargar las competencias. Intentá nuevamente.' }); } }, []);
  useEffect(() => { loadCompetitions(); }, [loadCompetitions]);
  const chooseCompetition = async (value) => { setCompetitionId(value); setResult(null); setReferences(null); if (!value) return; try { setReferences(await getResultReferences(value)); } catch (error) { setNotice({ error: true, text: formatResultImportError(error) }); } };
  const analyze = async (event) => {
    event.preventDefault(); if (!file || !competitionId) return; setBusy(true); setNotice(null); setResult(null);
    try { const [parsed, refs] = await Promise.all([parseResultFile(file), getResultReferences(competitionId)]); setReferences(refs); setResult(reconcileResultPreview(parsed, refs)); if (!parsed.ok) setNotice({ error: true, text: formatResultImportError(parsed) }); }
    catch (error) { setNotice({ error: true, text: formatResultImportError(error) }); } finally { setBusy(false); }
  };
  const resolveMapping = async (mapping, targetId) => {
    if (!targetId) return; setBusy(true); setNotice(null);
    try {
      const saved = await saveResultMapping({ ...mapping, targetId }); const nextMappings = [...(references?.mappings || []).filter((item) => item.id !== saved.id && !(item.provider === saved.provider && item.source_organization === saved.source_organization && item.external_code === saved.external_code)), saved];
      const next = { ...references, mappings: nextMappings }; setReferences(next); setResult((current) => current ? reconcileResultPreview(current, next) : current); setNotice({ text: 'Identidad guardada. La vista previa fue recalculada.' });
    } catch (error) { setNotice({ error: true, text: formatResultImportError(error) }); } finally { setBusy(false); }
  };
  const reconciliation = result?.reconciliation; const athleteByAlias = new Map((result?.preview?.athletes || []).map((item) => [item.sourceAlias, item.displayName]));
  return <section aria-labelledby="admin-results-title" className="space-y-6">
    <div><p className="text-xs font-bold uppercase tracking-[0.16em] text-asanda-deep">Operaciones deportivas</p><h1 id="admin-results-title" className="mt-2 font-display text-3xl font-bold sm:text-4xl">Importar resultados</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300">Procesá HY3 localmente, reconciliá las identidades y revisá una vista previa saneada. El archivo original y sus datos privados no salen del navegador.</p></div>
    <Notice notice={notice} />
    <form className={`${panel} grid gap-5 sm:grid-cols-2`} onSubmit={analyze}>
      <label className="text-sm font-bold">Competencia<select className={field} required value={competitionId} onChange={(event) => chooseCompetition(event.target.value)}><option value="">Seleccioná una competencia…</option>{competitions?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label className="text-sm font-bold">Archivo HY3 o CSV (fallback)<input className={`${field} file:mr-3 file:border-0 file:bg-asanda-mist file:px-3 file:py-2 file:font-bold dark:file:bg-slate-700`} type="file" accept=".hy3,.csv,text/csv" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label>
      <p className="text-xs leading-5 text-slate-600 dark:text-slate-300 sm:col-span-2">HY3 es el formato principal. CSV sólo acepta columnas públicas de alias, evento, tiempo, estado, puesto y nota.</p>
      <div className="sm:col-span-2"><button type="submit" disabled={busy || !file || !competitionId} className="inline-flex min-h-11 items-center gap-2 rounded-md bg-asanda-orange-strong px-5 font-bold text-white disabled:opacity-60"><Upload size={17} aria-hidden="true" />{busy ? 'Procesando localmente…' : 'Generar vista previa saneada'}</button></div>
    </form>
    {!competitions && !notice && <p role="status" className={panel}>Cargando competencias…</p>}
    {result?.ok && result.preview && <>
      <section className={panel} aria-labelledby="preview-title"><div className="flex items-start gap-3"><FileCheck2 className="mt-1 shrink-0 text-asanda-orange" aria-hidden="true" /><div><h2 id="preview-title" className="text-2xl font-bold">Vista previa saneada</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{result.preview.meetName} · versión {result.preview.version} · {result.checksum ? `checksum ${result.checksum}` : 'checksum disponible al ejecutar en el navegador'}</p></div></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-4"><div><dt className="font-bold">Registros</dt><dd>{Object.values(result.preview.recordCounts).reduce((sum, count) => sum + count, 0)}</dd></div><div><dt className="font-bold">Atletas</dt><dd>{result.preview.athletes.length}</dd></div><div><dt className="font-bold">Resultados</dt><dd>{result.preview.results.length}</dd></div><div><dt className="font-bold">Relevos</dt><dd>{result.preview.relays.length}</dd></div></dl></section>
      <section className={panel} aria-labelledby="mapping-title"><div className="flex items-center gap-3"><Users className="text-asanda-orange" aria-hidden="true" /><h2 id="mapping-title" className="text-2xl font-bold">Reconciliación de identidades</h2></div><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Cada alias debe apuntar a un registro ASANDA antes de habilitar una revisión de importación.</p><div className="mt-4 space-y-3" aria-label="Reconciliación de identidades">{reconciliation?.mappings.map((mapping) => { const options = mapping.mappingKind === 'athlete' ? references.athletes : references.organizations; return <div key={`${mapping.mappingKind}-${mapping.externalCode}`} className="grid gap-3 border-t border-asanda-line pt-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end dark:border-slate-700"><div><p className="text-xs font-bold uppercase tracking-wide text-asanda-deep">{mapping.mappingKind === 'athlete' ? 'Atleta' : 'Equipo'}</p><p className="font-semibold">{mapping.externalCode}</p></div><label className="text-sm font-bold">Registro ASANDA<select className={field} aria-label={`Resolver ${mapping.externalCode}`} defaultValue={mapping.targetId} disabled={busy} onChange={(event) => resolveMapping(mapping, event.target.value)}><option value="">Sin resolver</option>{options.map((item) => <option key={item.id} value={item.id}>{targetName(item)}</option>)}</select></label><p className={`text-sm font-bold ${mapping.resolutionStatus === 'resolved' ? 'text-emerald-700 dark:text-emerald-300' : 'text-amber-700 dark:text-amber-300'}`}>{mapping.resolutionStatus === 'resolved' ? 'Resuelta' : 'Pendiente'}</p></div>; })}</div></section>
      <section className={panel} aria-labelledby="validation-title"><h2 id="validation-title" className="text-2xl font-bold">Validación previa</h2>{reconciliation?.errors.length > 0 ? <div role="alert" className="mt-4 space-y-2 text-sm text-red-800 dark:text-red-200"><p className="font-bold">La vista previa está bloqueada:</p><ul className="list-disc space-y-1 pl-5">{reconciliation.errors.map((item, index) => <li key={`${item.code}-${item.sourceAlias}-${index}`}>{item.sourceAlias}: {item.message}</li>)}</ul></div> : <p role="status" className="mt-4 flex items-center gap-2 font-semibold text-emerald-700 dark:text-emerald-300"><CheckCircle2 size={17} aria-hidden="true" />Todas las referencias y resultados están listos para revisión transaccional.</p>}<p className="mt-4 text-xs text-slate-600 dark:text-slate-300">Los resultados se muestran sin números de identidad, fechas exactas de nacimiento, contactos ni bytes del archivo.</p></section>
      <section className={panel} aria-labelledby="rows-title"><h2 id="rows-title" className="text-2xl font-bold">Resultados detectados</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><caption className="sr-only">Resultados detectados en la vista previa</caption><thead><tr className="border-b border-asanda-line text-xs uppercase tracking-wide dark:border-slate-700"><th className="p-2">Atleta</th><th className="p-2">Evento</th><th className="p-2">Tiempo</th><th className="p-2">Estado</th><th className="p-2">Puesto</th></tr></thead><tbody>{result.preview.results.map((row) => <tr key={row.sourceAlias} className="border-b border-asanda-line dark:border-slate-700"><td className="p-2">{athleteByAlias.get(row.athleteAlias) || row.athleteAlias}</td><td className="p-2">{row.eventAlias}</td><td className="p-2">{row.timeText || '—'}</td><td className="p-2">{row.status}</td><td className="p-2">{row.place || '—'}</td></tr>)}</tbody></table></div></section>
    </>}
    {busy && <p role="status" className="sr-only">Procesando resultado</p>}
  </section>;
}
