import React, { useEffect, useRef, useState } from 'react';
import { Award } from 'lucide-react';
import { useAdminSession } from './AdminSessionContext';
import AthleteAchievementForm from './AthleteAchievementForm';
import AthleteAchievementList from './AthleteAchievementList';
import { deleteAthleteAchievementGroup, describeAchievementError, formatAchievementError, getAthleteAchievementReferences, listAthleteAchievements, publishAthleteAchievementGroup, saveAthleteAchievementGroup } from '../services/admin/athleteAchievements';

const AthleteAchievementPanel = ({ athleteId }) => {
  const { profile } = useAdminSession(); const administrator = profile?.role === 'administrator';
  const [items, setItems] = useState(null); const [references, setReferences] = useState({ events: [], records: [] }); const [editing, setEditing] = useState(null); const [busyId, setBusyId] = useState(null); const [notice, setNotice] = useState(null); const noticeRef = useRef(null);
  const load = async (isActive = () => true) => { const [achievements, loadedReferences] = await Promise.all([listAthleteAchievements(athleteId), getAthleteAchievementReferences(athleteId)]); const records = new Map(loadedReferences.records.map((record) => [record.id, record])); const loadedItems = achievements.map((item) => ({ ...item, children: item.children.map((child) => ({ ...child, recordPublishedAt: records.get(child.recordId)?.publishedAt || null })) })); if (isActive()) { setItems(loadedItems); setReferences(loadedReferences); } return loadedItems; };
  useEffect(() => { if (!administrator) return undefined; let active = true; setItems(null); setNotice(null); load(() => active).catch((error) => { if (active) { setItems([]); setNotice({ error: true, text: formatAchievementError(error) }); } }); return () => { active = false; }; }, [athleteId, administrator]);
  useEffect(() => { if (notice?.error) noticeRef.current?.focus(); }, [notice]);
  if (!administrator) return null;
  const resultId = (result) => String(typeof result === 'string' ? result : result?.group_id || '').trim();
  const childValues = (child) => ({ eventDefinitionId: String(child?.eventDefinitionId || '').trim(), podiumPlace: child?.podiumPlace == null || child.podiumPlace === '' ? '' : String(Number(child.podiumPlace)), participationOutcome: String(child?.participationOutcome || '').trim(), recordId: String(child?.recordId || '').trim(), legacyEventLabel: String(child?.legacyEventLabel || '').trim(), legacyPayload: child?.legacyPayload || null, legacySourceIdentifier: String(child?.legacySourceIdentifier || '').trim() });
  const childSignatures = (children) => children.map((child) => JSON.stringify(childValues(child))).sort();
  const persistedValuesMatch = (loaded, submitted) => loaded?.publicationStatus === 'draft' && loaded.type === submitted.type && loaded.title === submitted.title.trim() && loaded.competitionName === submitted.competitionName.trim() && loaded.location === submitted.location.trim() && loaded.achievedOn === submitted.achievedOn.trim() && JSON.stringify(childSignatures(loaded.children)) === JSON.stringify(childSignatures(submitted.children));
  const run = async (key, action, success, confirm, inline = false) => { setBusyId(key); setNotice(null); let actionResult; try { actionResult = await action(); } catch (error) { const detail = describeAchievementError(error); if (!inline || !detail.field) setNotice({ error: true, text: detail.message }); setBusyId(null); return { ok: false, error: detail }; } try { const loadedItems = await load(); if (!confirm(actionResult, loadedItems)) throw new Error(); setNotice({ error: false, text: success }); return { ok: true }; } catch { const detail = describeAchievementError(new Error('ACHIEVEMENT_PERSISTENCE_UNCONFIRMED')); setNotice({ error: true, text: detail.message }); return { ok: false, error: detail }; } finally { setBusyId(null); } };
  const save = async (values) => { const result = await run(values.id || 'create', () => saveAthleteAchievementGroup(athleteId, values), values.id ? 'Competencia actualizada.' : 'Competencia agregada como borrador.', (saved, loadedItems) => { const id = resultId(saved); const loaded = loadedItems.find((item) => item.id === id); return Boolean(id) && persistedValuesMatch(loaded, values); }, true); if (result.ok) setEditing(null); return result; };
  const act = async (item, action) => { const publishing = action === 'publish'; const result = await run(item.id, publishing ? () => publishAthleteAchievementGroup(item.id) : () => deleteAthleteAchievementGroup(item.id), publishing ? 'Competencia publicada.' : 'Competencia eliminada.', (changed, loadedItems) => { const id = resultId(changed); if (!id || id !== item.id) return false; const loaded = loadedItems.find((candidate) => candidate.id === id); return publishing ? loaded?.publicationStatus === 'published' : !loaded; }); if (result.ok) setEditing((current) => current?.id === item.id ? null : current); };
  return <section aria-labelledby="athlete-achievement-title" className="min-w-0 rounded-[14px] border border-asanda-line bg-white p-5 sm:p-6 dark:border-slate-700 dark:bg-dark-surface"><div className="flex items-start gap-3"><Award className="mt-1 shrink-0 text-asanda-deep dark:text-slate-200" aria-hidden="true" /><div><h2 id="athlete-achievement-title" className="font-display text-2xl font-bold">Logros deportivos</h2><p className="mt-1 text-sm leading-6 text-slate-600 dark:text-slate-300">Registrá una competencia con sus resultados oficiales. No hace falta adjuntar pruebas.</p><p className="mt-2 text-sm font-semibold leading-6 text-asanda-deep dark:text-slate-200">Estos datos se guardan por separado: usá “Guardar logro como borrador” y después publicalo desde su propia tarjeta. Publicar la ficha del atleta no guarda ni publica este formulario.</p></div></div>{notice && <p ref={noticeRef} tabIndex={notice.error ? -1 : undefined} role={notice.error ? 'alert' : 'status'} className={`mt-4 rounded-md border p-3 text-sm ${notice.error ? 'border-red-200 bg-red-50 text-red-800 dark:border-red-900 dark:bg-red-950 dark:text-red-200' : 'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{notice.text}</p>}<AthleteAchievementForm events={references.events} records={references.records} editing={editing} canCreate={(items || []).length < 6} busy={Boolean(busyId)} onSubmit={save} onCancel={() => setEditing(null)} />{items === null ? <p role="status" className="mt-5 text-sm">Cargando logros…</p> : <AthleteAchievementList items={items} busyId={busyId} onEdit={setEditing} onPublish={(item) => act(item, 'publish')} onDelete={(item) => act(item, 'delete')} />}</section>;
};

export default AthleteAchievementPanel;
